language: node_js

services:
  - docker
before_script:
  - git clone https://github.com/lucas-marchi/tac-express
script:
  - docker build -t minha-aplicacao .
  - docker run -d --name minha-aplicacao-container minha-aplicacao
after_script:
  - docker stop minha-aplicacao-container
  - docker rm minha-aplicacao-container